### ISSUE TITLE
Intro needs to be edited and made more friendly

### ISSUE THREAD

**Issue by torgo** [w3cping/security-questionnaire#20]
This document's introduction section is too long, contains overly complex wording for things that should be simple and straightforward and in some cases contains misleading advice. For example, the paragraph on how to interact with PING, should arguably be removed as we don't want every group to talk to ping first

**Comment by samuelweiler** [comment]
Closing this in favor of the issue in the tag repo: https://github.com/w3ctag/security-questionnaire/issues/46
