### ISSUE TITLE
[Meta] There should only be one issue tracker

### ISSUE THREAD

**Issue by hober** [w3cping/security-questionnaire#21]
(With my TAG hat on)

We noticed today that there are two issue trackers associated with this document, a [w3cping one](https://github.com/w3cping/security-questionnaire/issues) and a [w3ctag one](https://github.com/w3ctag/security-questionnaire/issues). This is confusing, and resulted in different TAG members filing issues in different places today. The questionnaire itself links to both of these (one under "Issue Tracking" and one under "Bug Reports."

We acknowledge that this document is a joint work item, and we're not picky about which issue tracker gets used. But please just use one, and please remove the redundant link from the document's front matter.

**Comment by samuelweiler** [comment]
We agree.  I've added headers around this w3cping repo directing issues to the TAG repo.  I'm not sure where the link to jason's personal repo is coming from.  I'll add a note over in the TAG issue:
https://github.com/w3ctag/security-questionnaire/issues/47
encouraging Lukasz to sort that.  (I can't reopen that issue. Perhaps you can?)
